### ISSUE TITLE
Enable two-factor authentication

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/gu-who#1]
Please enable two-factor authentication in your GitHub settings. This will add an additional layer of security to your account and make the Financial Times less vulnerable to attacks.

Here is how: https://github.com/blog/1614-two-factor-authentication
- [ ] @stuhar
- [ ] @syymza
- [ ] @vnadgir-ft
- [ ] @yolandeleungFT
- [ ] @yunhan0
- [x] @Zapadlo
- [ ] @moranr77
- [ ] @musthemag
- [ ] @Nesze
- [ ] @next-team
- [ ] @noelbuce
- [ ] @patrickkettner
- [ ] @pauloneillft
- [ ] @radiodario
- [ ] @RenielR
- [ ] @reoneljose
- [ ] @rtbaker
- [ ] @simonwilliamsFT
- [ ] @GeorgeBogdis
- [ ] @guyvalerio
- [ ] @Jesslipson
- [ ] @jonathantneal
- [ ] @karinagp
- [ ] @kovacshuni
- [ ] @Loita123
- [ ] @a-rhombus
- [ ] @AndrewWatkins
- [ ] @bbinto
- [ ] @bedemccarthy
- [ ] @caridy
- [ ] @catalin-ilea
- [ ] @cheekymonkat
- [ ] @chris-mooney
- [ ] @christinetecson
- [ ] @clmntnbrn
- [ ] @DorothyAngeles
- [ ] @ervilletalaoc11
- [ ] @freeseus

If you have any questions or need any help, please contact the Security Working Group security.working.group@ft.com

**Comment by caridy** [comment]
- [x] @caridy

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
